global:
  scrape_interval:     5s 
  evaluation_interval: 5s 

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'prometheus-test'
    static_configs:
      - targets: ['test-prometheus-example.192.168.64.2.nip.io']
