startDelaySecs: 5
ssl: false
blacklistObjectNames: ["java.lang:*"]
#whitelistObjectNames: ["org.apache.camel:*"]
rules:
# Context level
  - pattern: 'org.apache.camel<context=([^,]+), type=context, name=([^,]+)><>ExchangesCompleted'
    name: org.apache.camel.ExchangesCompleted
    help: Exchanges Completed
    type: COUNTER
    labels:
      context: $1
      type: context
  - pattern: 'org.apache.camel<context=([^,]+), type=context, name=([^,]+)><>ExchangesFailed'
    name: org.apache.camel.ExchangesFailed
    help: Exchanges ExchangesFailed
    type: COUNTER
    labels:
      context: $1
      type: context
  - pattern: 'org.apache.camel<context=([^,]+), type=context, name=([^,]+)><>ExchangesInflight'
    name: org.apache.camel.ExchangesInflight
    help: Exchanges Inflight
    type: COUNTER
    labels:
      context: $1
      type: context
  - pattern: 'org.apache.camel<context=([^,]+), type=context, name=([^,]+)><>ExchangesTotal'
    name: org.apache.camel.ExchangesTotal
    help: Exchanges Total
    type: COUNTER
    labels:
      context: $1
      type: context
  - pattern: 'org.apache.camel<context=([^,]+), type=context, name=([^,]+)><>ExchangesTotal'
    name: org.apache.camel.ExchangesTotal
    help: Exchanges Total
    type: COUNTER
    labels:
      context: $1
      type: context
  - pattern: 'org.apache.camel<context=([^,]+), type=context, name=([^,]+)><>FailuresHandled'
    name: org.apache.camel.FailuresHandled
    help: Failures Handled
    labels:
        context: $1
        type: context
    type: COUNTER
  - pattern: 'org.apache.camel<context=([^,]+), type=context, name=([^,]+)><>ExternalRedeliveries'
    name: org.apache.camel.ExternalRedeliveries
    help: External Redeliveries
    labels:
        context: $1
        type: context
    type: COUNTER
  - pattern: 'org.apache.camel<context=([^,]+), type=context, name=([^,]+)><>MaxProcessingTime'
    name: org.apache.camel.MaxProcessingTime
    help: Maximum Processing Time
    labels:
        context: $1
        type: context
    type: GAUGE
  - pattern: 'org.apache.camel<context=([^,]+), type=context, name=([^,]+)><>MeanProcessingTime'
    name: org.apache.camel.MeanProcessingTime
    help: Mean Processing Time
    labels:
        context: $1
        type: context
    type: GAUGE
  - pattern: 'org.apache.camel<context=([^,]+), type=context, name=([^,]+)><>MinProcessingTime'
    name: org.apache.camel.MinProcessingTime
    help: Minimum Processing Time
    labels:
        context: $1
        type: context
    type: GAUGE
  - pattern: 'org.apache.camel<context=([^,]+), type=context, name=([^,]+)><>Redeliveries'
    name: org.apache.camel.Redeliveries
    help: Redeliveries
    labels:
        context: $1
        type: context
    type: GAUGE
  - pattern: 'org.apache.camel<context=([^,]+), type=context, name=([^,]+)><>TotalProcessingTime'
    name: org.apache.camel.TotalProcessingTime
    help: Total Processing Time
    labels:
        context: $1
        type: context
    type: GAUGE
  - pattern: 'org.apache.camel<context=([^,]+), type=consumers, name=([^,]+)><>InflightExchanges'
    name: org.apache.camel.InflightExchanges
    help: Inflight Exchanges
    labels:
        context: $1
        type: context
    type: GAUGE


# Route level
  - pattern: 'org.apache.camel<context=([^,]+), type=routes, name=([^,]+)><>ExchangesCompleted'
    name: org.apache.camel.ExchangesCompleted
    help: Exchanges Completed
    type: COUNTER
    labels:
      context: $1
      route: $2
      type: routes
  - pattern: 'org.apache.camel<context=([^,]+), type=routes, name=([^,]+)><>ExchangesFailed'
    name: org.apache.camel.ExchangesFailed
    help: Exchanges ExchangesFailed
    type: COUNTER
    labels:
      context: $1
      route: $2
      type: routes
  - pattern: 'org.apache.camel<context=([^,]+), type=routes, name=([^,]+)><>ExchangesInflight'
    name: org.apache.camel.ExchangesInflight
    help: Exchanges Inflight
    type: COUNTER
    labels:
      context: $1
      route: $2
      type: routes
  - pattern: 'org.apache.camel<context=([^,]+), type=routes, name=([^,]+)><>ExchangesTotal'
    name: org.apache.camel.ExchangesTotal
    help: Exchanges Total
    type: COUNTER
    labels:
      context: $1
      route: $2
      type: routes
  - pattern: 'org.apache.camel<context=([^,]+), type=routes, name=([^,]+)><>ExchangesTotal'
    name: org.apache.camel.ExchangesTotal
    help: Exchanges Total
    type: COUNTER
    labels:
      context: $1
      route: $2
      type: routes
  - pattern: 'org.apache.camel<context=([^,]+), type=routes, name=([^,]+)><>FailuresHandled'
    name: org.apache.camel.FailuresHandled
    help: Failures Handled
    labels:
        context: $1
        route: $2
        type: routes
    type: COUNTER
  - pattern: 'org.apache.camel<context=([^,]+), type=routes, name=([^,]+)><>ExternalRedeliveries'
    name: org.apache.camel.ExternalRedeliveries
    help: External Redeliveries
    labels:
        context: $1
        route: $2
        type: routes
    type: COUNTER
  - pattern: 'org.apache.camel<context=([^,]+), type=routes, name=([^,]+)><>MaxProcessingTime'
    name: org.apache.camel.MaxProcessingTime
    help: Maximum Processing Time
    labels:
        context: $1
        route: $2
        type: routes
    type: GAUGE
  - pattern: 'org.apache.camel<context=([^,]+), type=routes, name=([^,]+)><>MeanProcessingTime'
    name: org.apache.camel.MeanProcessingTime
    help: Mean Processing Time
    labels:
        context: $1
        route: $2
        type: routes
    type: GAUGE
  - pattern: 'org.apache.camel<context=([^,]+), type=routes, name=([^,]+)><>MinProcessingTime'
    name: org.apache.camel.MinProcessingTime
    help: Minimum Processing Time
    labels:
        context: $1
        route: $2
        type: routes
    type: GAUGE
  - pattern: 'org.apache.camel<context=([^,]+), type=routes, name=([^,]+)><>Redeliveries'
    name: org.apache.camel.Redeliveries
    help: Redeliveries
    labels:
        context: $1
        route: $2
        type: routes
    type: GAUGE
  - pattern: 'org.apache.camel<context=([^,]+), type=routes, name=([^,]+)><>TotalProcessingTime'
    name: org.apache.camel.TotalProcessingTime
    help: Total Processing Time
    labels:
        context: $1
        route: $2
        type: routes
    type: GAUGE
  - pattern: 'org.apache.camel<context=([^,]+), type=routes, name=([^,]+)><>InflightExchanges'
    name: org.apache.camel.InflightExchanges
    help: Inflight Exchanges
    labels:
        context: $1
        route: $2
        type: routes
    type: GAUGE


# Processor level
  - pattern: 'org.apache.camel<context=([^,]+), type=processors, name=([^,]+)><>ExchangesCompleted'
    name: org.apache.camel.ExchangesCompleted
    help: Exchanges Completed
    type: COUNTER
    labels:
      context: $1
      processor: $2
      type: processors
  - pattern: 'org.apache.camel<context=([^,]+), type=processors, name=([^,]+)><>ExchangesFailed'
    name: org.apache.camel.ExchangesFailed
    help: Exchanges ExchangesFailed
    type: COUNTER
    labels:
      context: $1
      processor: $2
      type: processors
  - pattern: 'org.apache.camel<context=([^,]+), type=processors, name=([^,]+)><>ExchangesInflight'
    name: org.apache.camel.ExchangesInflight
    help: Exchanges Inflight
    type: COUNTER
    labels:
      context: $1
      processor: $2
      type: processors
  - pattern: 'org.apache.camel<context=([^,]+), type=processors, name=([^,]+)><>ExchangesTotal'
    name: org.apache.camel.ExchangesTotal
    help: Exchanges Total
    type: COUNTER
    labels:
      context: $1
      processor: $2
      type: processors
  - pattern: 'org.apache.camel<context=([^,]+), type=processors, name=([^,]+)><>ExchangesTotal'
    name: org.apache.camel.ExchangesTotal
    help: Exchanges Total
    type: COUNTER
    labels:
      context: $1
      processor: $2
      type: processors
  - pattern: 'org.apache.camel<context=([^,]+), type=processors, name=([^,]+)><>FailuresHandled'
    name: org.apache.camel.FailuresHandled
    help: Failures Handled
    labels:
        context: $1
        processor: $2
        type: processors
    type: COUNTER
  - pattern: 'org.apache.camel<context=([^,]+), type=processors, name=([^,]+)><>ExternalRedeliveries'
    name: org.apache.camel.ExternalRedeliveries
    help: External Redeliveries
    labels:
        context: $1
        processor: $2
        type: processors
    type: COUNTER
  - pattern: 'org.apache.camel<context=([^,]+), type=processors, name=([^,]+)><>MaxProcessingTime'
    name: org.apache.camel.MaxProcessingTime
    help: Maximum Processing Time
    labels:
        context: $1
        processor: $2
        type: processors
    type: GAUGE
  - pattern: 'org.apache.camel<context=([^,]+), type=processors, name=([^,]+)><>MeanProcessingTime'
    name: org.apache.camel.MeanProcessingTime
    help: Mean Processing Time
    labels:
        context: $1
        processor: $2
        type: processors
    type: GAUGE
  - pattern: 'org.apache.camel<context=([^,]+), type=processors, name=([^,]+)><>MinProcessingTime'
    name: org.apache.camel.MinProcessingTime
    help: Minimum Processing Time
    labels:
        context: $1
        processor: $2
        type: processors
    type: GAUGE
  - pattern: 'org.apache.camel<context=([^,]+), type=processors, name=([^,]+)><>Redeliveries'
    name: org.apache.camel.Redeliveries
    help: Redeliveries
    labels:
        context: $1
        processor: $2
        type: processors
    type: GAUGE
  - pattern: 'org.apache.camel<context=([^,]+), type=processors, name=([^,]+)><>TotalProcessingTime'
    name: org.apache.camel.TotalProcessingTime
    help: Total Processing Time
    labels:
        context: $1
        processor: $2
        type: processors
    type: GAUGE
  - pattern: 'org.apache.camel<context=([^,]+), type=processors, name=([^,]+)><>InflightExchanges'
    name: org.apache.camel.InflightExchanges
    help: Inflight Exchanges
    labels:
        context: $1
        processor: $2
        type: processors
    type: COUNTER

# Consumers
  - pattern: 'org.apache.camel<context=([^,]+), type=consumers, name=([^,]+)><>InflightExchanges'
    name: org.apache.camel.InflightExchanges
    help: Inflight Exchanges
    labels:
        context: $1
        consumer: $2
        type: consumers
    type: GAUGE

# Services
  - pattern: 'org.apache.camel<context=([^,]+), type=services, name=([^,]+)><>MaxDuration'
    name: org.apache.camel.MaxDuration
    help: Inflight Exchanges
    labels:
        context: $1
        service: $2
        type: services
    type: GAUGE
  - pattern: 'org.apache.camel<context=([^,]+), type=services, name=([^,]+)><>MeanDuration'
    name: org.apache.camel.MeanDuration
    help: Inflight Exchanges
    labels:
        context: $1
        service: $2
        type: services
    type: GAUGE
  - pattern: 'org.apache.camel<context=([^,]+), type=services, name=([^,]+)><>MinDuration'
    name: org.apache.camel.MinDuration
    help: Inflight Exchanges
    labels:
        context: $1
        service: $2
        type: services
    type: GAUGE
  - pattern: 'org.apache.camel<context=([^,]+), type=services, name=([^,]+)><>TotalDuration'
    name: org.apache.camel.TotalDuration
    help: Inflight Exchanges
    labels:
        context: $1
        service: $2
        type: services
    type: GAUGE
  - pattern: 'org.apache.camel<context=([^,]+), type=services, name=([^,]+)><>ThreadsBlocked'
    name: org.apache.camel.ThreadsBlocked
    help: Inflight Exchanges
    labels:
        context: $1
        service: $2
        type: services
    type: GAUGE
  - pattern: 'org.apache.camel<context=([^,]+), type=services, name=([^,]+)><>ThreadsInterrupted'
    name: org.apache.camel.ThreadsInterrupted
    help: Inflight Exchanges
    labels:
        context: $1
        service: $2
        type: services
    type: GAUGE